### ISSUE TITLE
Failed to generate payload

### ISSUE THREAD

**Issue by andreibarbu93** [MythicAgents/merlin#13]
Hello! I can't generate any merlin payload from mythic version 3.0.1-rc46, using the http profile. I will attach the error and the configuration of the payload. Maybe you can see something i do wrong, and help me please?

![1](https://github.com/MythicAgents/merlin/assets/136431577/273a7c78-9a13-4443-8f19-0d87f80269c3)

![2](https://github.com/MythicAgents/merlin/assets/136431577/85e0e01a-3b3f-4439-9159-b05daae37546)

![3](https://github.com/MythicAgents/merlin/assets/136431577/30e05b7f-0d3e-4193-b0dc-c8cf3045f06e)

**Comment by Ne0nd0g** [comment]
Thanks for reporting this, I will look into it. I did a quick test on my host and was not able to duplicate. Can you share the output of `./mythic-cli version` from your host? Do you get the same error if you don't make any modifications the Agent and HTTP profile sections?

**Comment by andreibarbu93** [comment]
[*] mythic-cli version:    v0.2.1
[*] Mythic Server version: v3.0.1-rc46
[*] React UI Version:      v0.1.15-rc38

And yes, its the same error with default profiles.

**Comment by Ne0nd0g** [comment]
> Failed to send payload back to Mythic: Failed to send payload to Mythic with status code: 401

At first glance, the error seems to be with Mythic. Can you restart the host and then run `./mythic-cli start` and see if the problem persists?

**Comment by its-a-feature** [comment]
When payloads are built, the actual final payload itself it shipped to Mythic via an HTTP request and the metadata about the build process is sent back via RabbitMQ (this is because the payloads can be massive in size and message queues are meant for smaller messages). What you're seeing indicates to me that the payload built successfully, but then failed to submit the file back to Mythic. This could be for a few reasons, but:

* Merlin was installed via mythic-cli and is running locally to Mythic right?
* Can you try building again, then run `./mythic-cli logs merlin` and `./mythic-cli logs mythic_server` and reply with those outputs?

**Comment by andreibarbu93** [comment]
I reinstalled on a clean server and now it works! I gave more ram and cpu! I can't see why it wasn't working but now its alright! Thanks for taking your time in order to help!
